spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: xxxxx
      base-url: xxxx
    zhipuai:
      api-key: xxxx
      base-url: https://open.bigmodel.cn/api/paas

    ollama:
      base-url: http://localhost:11434
      model: llava

    vectorstore:
      redis:
        uri: redis://localhost:6379