spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: sk-fTwEKce0RcVz5W2AA2Dc811e0e304944A91dB31a7a16Bf38
      base-url: https://api.xty.app
    zhipuai:
      api-key: 4bfe98b66ec334622a108e99b34f04cc.LWOzG8jHPLCgZK5Y
      base-url: https://open.bigmodel.cn/api/paas

    ollama:
      base-url: http://localhost:11434
      model: llava

    vectorstore:
      redis:
        uri: redis://localhost:6379